fix resizing on arch linux host

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -641,26 +641,20 @@ _EOF_
     outputn "Copying cloud image ($(basename ${IMAGE}))"
     DISK=${VMNAME}.qcow2
     qemu-img create -q -f qcow2 -F qcow2 -b $IMAGE $DISK && ok
+    
+     echo "change ownership of DISK"
+    sudo chown nobody:kvm ${DISK}  
+
     if $RESIZE_DISK
     then
         outputn "Resizing the disk to $DISK_SIZE"
         # Workaround to prevent virt-resize from renumbering partitions and breaking grub
         # See https://bugzilla.redhat.com/show_bug.cgi?id=1472039
         # Ubuntu will automatically grow the partition to the new size on its first boot
-        case "$DISTRO" in
-        ubuntu*|amazon2)
-            qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log \
+            sudo qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log \
                 && ok \
-                || die "Could not resize disk."
-            ;;
-        *)
-            qemu-img create -f qcow2 \
-                -o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
-                && virt-resize --quiet --expand /dev/sda1 $DISK $DISK.new &>> ${VMNAME}.log \
-                && (mv $DISK.new $DISK && ok) \
-                || die "Could not resize disk."
-            ;;
-        esac
+                || die "Could not resize ubuntu disk."
+        
     fi
 
     # Create CD-ROM ISO with cloud-init config
@@ -677,6 +671,9 @@ _EOF_
             && ok \
             || die "Could not generate ISO."
     fi
+
+    echo "change ownership of CI_ISO"
+    sudo chown nobody:kvm ${CI_ISO}
 
     # Create new storage pool for new VM
     run "Creating storage pool" \
@@ -723,9 +720,7 @@ _EOF_
     CI_ISO_OPTION="$(param --disk ${CI_ISO_PARAMS})"
     GRAPHICS_OPTION="$(param --graphics ${GRAPHICS_PARAMS})"
 
-    echo "change ownership of DISK and CI_ISO"
-    sudo chown nobody:kvm ${DISK}
-    sudo chown nobody:kvm ${CI_ISO}
+    
     # Call virt-install to import the cloud image and create a new VM
     run "Installing the domain" \
         virt-install --import \
